import { useEffect, useState } from 'react';

const templates = [
  { name: 'Nova', label: 'Cinematic example', price: '$49', className: 'nova', description: 'A polished example interface showing how an AnimeFusion installation can look.' },
  { name: 'Kairo', label: 'Content-first example', price: '$59', className: 'kairo', description: 'A catalogue-focused example built around discovery, libraries and editorial content.' },
  { name: 'Aether', label: 'Minimal example', price: '$39', className: 'aether', description: 'A quiet example visual system for installations that prefer a clean, lightweight look.' },
];

const features = [
  ['01', 'Self-hosted core', 'Install AnimeFusion on infrastructure you control. Your site, database and configuration stay yours.'],
  ['02', 'Automatic importing', 'Scheduled jobs can pull anime metadata, seasons and episodes into your local catalogue.'],
  ['03', 'Provider architecture', 'Keep content and streaming sources behind a replaceable provider layer.'],
  ['04', 'Powerful admin', 'Manage users, content, history, sources, branding, settings and platform data from one workspace.'],
  ['05', 'Example templates', 'Use the example designs as a starting point and change the visual experience without rebuilding the core.'],
  ['06', 'Developer-friendly stack', 'Node, React, Vite and PostgreSQL give you a familiar stack to inspect and extend.'],
  ['07', 'Cron & automation', 'Background jobs handle recurring imports and other repetitive platform work automatically.'],
  ['08', 'SEO-ready foundation', 'Clean content routes, metadata and structured page architecture provide a strong foundation for discovery.'],
];

const steps = [
  ['01', 'Get AnimeFusion', 'Start with the core and choose an example template or your own frontend direction.'],
  ['02', 'Upload it to your server', 'Use your own hosting, VPS or infrastructure. AnimeFusion is designed to be self-hosted.'],
  ['03', 'Run the installer', 'Open /install, connect PostgreSQL, configure the environment and create your administrator.'],
  ['04', 'Configure your installation', 'Set up the content and streaming providers that your own installation will use.'],
  ['05', 'Launch your community', 'Finish your branding and settings, then run your own AnimeFusion site.'],
];

const faqs = [
  ['Is AnimeFusion a hosted service?', 'No. AnimeFusion is designed as self-hosted software. You run the installation on infrastructure you control.'],
  ['Are the templates finished products?', 'The storefront templates are example designs. They show possible visual directions for AnimeFusion and can be customized for your own installation.'],
  ['Do the example templates require embed-provider setup?', 'No. The example templates are only frontend examples. Provider configuration belongs to the AnimeFusion installation itself, not the visual template.'],
  ['Can I change the design later?', 'Yes. The core and presentation are intended to stay separate so you can change the frontend without throwing away the platform underneath.'],
];

const pageStyles = `
.page{min-height:calc(100vh - 72px);background:#fff}.page-hero{max-width:1180px;margin:auto;padding:100px 24px 75px}.page-kicker{font-size:10px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:#888}.page-hero h1{max-width:850px;margin:18px 0 22px;font:600 clamp(50px,7vw,82px)/.94 'Space Grotesk';letter-spacing:-.075em}.page-hero h1 span{color:#999}.page-hero p{max-width:610px;margin:0;color:#737378;font-size:15px;line-height:1.8}.page-grid{max-width:1180px;margin:auto;padding:0 24px 120px}.template-page-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.example-note{margin:0 0 26px;padding:15px 18px;border:1px solid #e5e5e2;border-radius:12px;background:#f7f7f5;color:#777;font-size:11px;line-height:1.65}.feature-page-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.feature-page-card{min-height:210px;padding:28px;border:1px solid #e4e4e1;border-radius:18px;background:#fff}.feature-page-card small{color:#aaa;font-size:9px}.feature-page-card h3{margin:55px 0 9px;font:600 20px 'Space Grotesk';letter-spacing:-.04em}.feature-page-card p{margin:0;color:#777;font-size:12px;line-height:1.7}.auth-page{display:grid;place-items:center;min-height:calc(100vh - 72px);padding:55px 20px;background:#f6f6f4}.auth-card{width:min(440px,100%);padding:34px;border:1px solid #e1e1dd;border-radius:20px;background:#fff;box-shadow:0 25px 70px #1111110b}.auth-card h1{margin:0 0 8px;font:600 32px 'Space Grotesk';letter-spacing:-.05em}.auth-card>p{margin:0 0 28px;color:#777;font-size:12px;line-height:1.6}.auth-form{display:grid;gap:15px}.auth-form label{display:grid;gap:7px;color:#555;font-size:11px;font-weight:600}.auth-form input{height:46px;padding:0 13px;border:1px solid #dddcd8;border-radius:10px;background:#fff;color:#111;outline:none;font:13px 'DM Sans'}.auth-form input:focus{border-color:#111;box-shadow:0 0 0 3px #11111108}.auth-form button{height:46px;margin-top:4px;border:0;border-radius:10px;background:#111;color:#fff;font:600 12px 'DM Sans';cursor:pointer}.auth-switch{margin:20px 0 0;text-align:center;color:#888;font-size:11px}.auth-switch a{color:#111;font-weight:700}.home-example-label{position:absolute;top:13px;right:14px;z-index:4;padding:7px 9px;border:1px solid #ddd;border-radius:8px;background:#fff;color:#666;font-size:7px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.site-footer-simple{padding:30px 24px;border-top:1px solid #e8e8e5;color:#999;font-size:10px;text-align:center}.mobile-page-nav{display:none}@media(max-width:900px){.template-page-grid{grid-template-columns:1fr 1fr}.feature-page-grid{grid-template-columns:1fr}}@media(max-width:680px){.page-hero{padding-top:70px}.page-hero h1{font-size:clamp(46px,14vw,66px)}.template-page-grid{grid-template-columns:1fr}.feature-page-card h3{margin-top:38px}.auth-card{padding:27px}.mobile-page-nav{display:block}.nav-links{display:none}}
`;

function Logo(){return <span className="logo-mark"><span>AF</span></span>}

function go(path){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}

function Nav(){return <header className="navbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();go('/')}}><Logo/>AnimeFusion</a><nav className="nav-links"><a href="/" onClick={e=>{e.preventDefault();go('/')}}>Home</a><a href="/templates" onClick={e=>{e.preventDefault();go('/templates')}}>Templates</a><a href="/features" onClick={e=>{e.preventDefault();go('/features')}}>Features</a></nav><div className="nav-actions"><a className="login-link" href="/signin" onClick={e=>{e.preventDefault();go('/signin')}}>Sign in</a><a className="button button-dark button-small" href="/signup" onClick={e=>{e.preventDefault();go('/signup')}}>Get started <span>↗</span></a></div></header>}

function Button({children,href='/',light=false}){return <a className={`button ${light?'button-light':'button-dark'}`} href={href} onClick={e=>{if(href.startsWith('/')){e.preventDefault();go(href)}}}>{children}<span>↗</span></a>}

function ProductWindow(){return <div className="browser-window"><div className="browser-bar"><div className="browser-dots"><i/><i/><i/></div><div className="browser-url">Example Template · AnimeFusion</div><span className="browser-menu">•••</span></div><div className="product-window"><div className="product-app"><div className="product-nav"><strong><i>AF</i> ANIMEFUSION</strong><span>Home</span><span>Browse</span><span>Schedule</span><span>Community</span><em>⌕</em><small>●</small></div><div className="product-hero"><div className="hero-panel-copy"><label>EXAMPLE TEMPLATE</label><h3>A home<br/><b>for your community.</b></h3><p>A visual example powered by the AnimeFusion core.</p><div><b>Explore example</b><span>Browse library →</span></div></div><div className="hero-panel-art"><i/><strong/><span/></div></div><div className="product-row-title"><b>Continue watching</b><span>Example library →</span></div><div className="product-posters"><i/><i/><i/><i/><i/></div></div></div></div>}

function TemplateCard({template}){return <article className="market-card"><div className={`market-preview ${template.className}`}><div className="market-nav"><b>EXAMPLE TEMPLATE</b><span>Home&nbsp;&nbsp; Browse&nbsp;&nbsp; Search</span></div><div className="market-copy"><small>{template.label}</small><h3>{template.name}<br/><i>example.</i></h3><span>View example&nbsp; →</span></div><div className="market-art"><i/><i/><i/></div></div><div className="market-meta"><div><small>{template.label}</small><h3>{template.name} Example</h3><p>{template.description}</p></div><strong>{template.price}</strong></div><div className="market-actions"><a href="/templates" onClick={e=>{e.preventDefault();go('/templates')}}>View example <span>↗</span></a><a href="/signup" onClick={e=>{e.preventDefault();go('/signup')}}>Get started <span>→</span></a></div></article>}

function Footer(){return <footer className="site-footer-simple">AnimeFusion · Self-hosted anime platform software</footer>}

function Home(){return <><main><section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/>SELF-HOSTED ANIME PLATFORM</div><h1>Build a home <span>for your community.</span></h1><p className="hero-text">AnimeFusion gives you one reusable core for building, running and customizing your own anime platform.</p><div className="hero-actions"><Button href="/templates">Explore examples</Button><Button href="/features" light>See features</Button></div><div className="hero-notes"><span><b>01</b> Your infrastructure</span><span><b>02</b> Your database</span><span><b>03</b> Your frontend</span></div></div><div className="hero-visual"><div className="home-example-label">Example template</div><ProductWindow/></div></section><section className="intro section-pad"><span className="section-kicker">THE PLATFORM</span><div className="intro-grid"><h2>One core.<br/><span>Many ways to build.</span></h2><p>Keep the platform logic separate from the visual layer. AnimeFusion is designed around a reusable self-hosted core, while templates show different ways the frontend can look.</p></div></section><section className="features section-pad"><div className="section-heading"><div><span className="section-kicker">WHAT'S INSIDE</span><h2>The important pieces.</h2></div><p>Built around the parts you actually need to run an anime community platform.</p></div><div className="feature-grid">{features.slice(0,6).map(f=><article className="feature-card" key={f[0]}><div className="feature-top"><span>{f[0]}</span><span>↗</span></div><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section><section className="templates section-pad"><div className="section-heading"><div><span className="section-kicker">EXAMPLE TEMPLATES</span><h2>See possible directions.</h2></div><p>These are examples of the visual layer — not separate hosted services.</p></div><div className="template-grid">{templates.map(t=><TemplateCard key={t.name} template={t}/>)}</div></section><section className="process section-pad"><div className="process-copy"><span className="section-kicker">SELF-HOSTED FLOW</span><h2>From package<br/>to platform.</h2><p>You control the server and installation. The setup process connects the core to your own environment, then leaves you with a platform you can customize.</p><Button href="/features" light>Read about the core</Button></div><div className="steps">{steps.map(s=><div className="step" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><b>+</b></div>)}</div></section></main><Footer/></>}

function TemplatesPage(){return <><main className="page"><section className="page-hero"><span className="page-kicker">EXAMPLE TEMPLATES</span><h1>Visual starting points.<br/><span>Not another hosted service.</span></h1><p>Explore example frontend designs for AnimeFusion. The examples show how the same self-hosted core can be presented in different ways.</p></section><section className="page-grid"><div className="example-note"><b>Important:</b> these are example templates. They do not require embed-provider setup themselves. Provider configuration belongs to the AnimeFusion installation and its backend.</div><div className="template-page-grid">{templates.map(t=><TemplateCard key={t.name} template={t}/>)}</div></section></main><Footer/></>}

function FeaturesPage(){return <><main className="page"><section className="page-hero"><span className="page-kicker">FEATURES</span><h1>The core that keeps your <span>site together.</span></h1><p>AnimeFusion is built as a reusable platform core with a separate visual layer, so the architecture can stay consistent while the frontend changes.</p></section><section className="page-grid"><div className="feature-page-grid">{features.map(f=><article className="feature-page-card" key={f[0]}><small>{f[0]}</small><h3>{f[1]}</h3><p>{f[2]}</p></article>)}</div></section></main><Footer/></>}

function AuthPage({signup=false}){return <main className="auth-page"><section className="auth-card"><div style={{marginBottom:24}}><Logo/></div><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Create an AnimeFusion account to manage your purchases and access your software.':'Sign in to your AnimeFusion account.'}</p><form className="auth-form" onSubmit={e=>e.preventDefault()}>{signup&&<label>Name<input placeholder="Your name"/></label>}<label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label>{signup&&<label>Confirm password<input type="password" placeholder="••••••••"/></label>}<button type="submit">{signup?'Create account':'Sign in'} <span>→</span></button></form><p className="auth-switch">{signup?'Already have an account? ':'Need an account? '}<a href={signup?'/signin':'/signup'} onClick={e=>{e.preventDefault();go(signup?'/signin':'/signup')}}>{signup?'Sign in':'Create one'}</a></p></section></main>}

function App(){const [path,setPath]=useState(window.location.pathname.replace(/\/$/,'')||'/');useEffect(()=>{const handler=()=>setPath(window.location.pathname.replace(/\/$/,'')||'/');window.addEventListener('popstate',handler);return()=>window.removeEventListener('popstate',handler)},[]);const page=path==='/templates'?<TemplatesPage/>:path==='/features'?<FeaturesPage/>:path==='/signin'?<AuthPage/>:path==='/signup'?<AuthPage signup/>:<Home/>;return <div className="site-shell"><style>{pageStyles}</style><Nav/>{page}</div>}

export default App;
